### ISSUE TITLE
可能会有内存泄漏问题, 建议修改下面👇的属性为strong

### ISSUE THREAD

**Issue by binzi56** [xing3523/XMixScrollManager#1]
```
///主视图
@property (nonatomic, weak) UIScrollView *mainScrollView;  
///内容视图的横向scrollView父视图
@property (nonatomic, weak) UIScrollView *contentSuperScrollView;
```
建议将`weak`修改为`strong`, 这样`dealloc`的时候, 视图不会为`nil`, 内部的观察者可以移除;

**Comment by xing3523** [comment]
调了一晚上，没有找到场景发现会有内存泄漏。。。
这里用weak是不想也没必要强引用它们，如果观察者先于被观察者被释放时，触发observer时会崩溃，被观察者先被释放时，对应的观察者这里是self并没有影响，观察了个空气而已，对应的observer方法不会再被触发，self后面也会正常释放。观察者与被观察者就都正常被释放掉了。
如果你实际有遇到因此内存泄漏的问题麻烦具体描述下场景，我再试试情况

**Comment by binzi56** [comment]
> 调了一晚上，没有找到场景发现会有内存泄漏。。。
> 这里用weak是不想也没必要强引用它们，如果观察者先于被观察者被释放时，触发observer时会崩溃，被观察者先被释放时，对应的观察者这里是self并没有影响，观察了个空气而已，对应的observer方法不会再被触发，self后面也会正常释放。观察者与被观察者就都正常被释放掉了。
> 如果你实际有遇到因此内存泄漏的问题麻烦具体描述下场景，我再试试情况

这里附张`bugly`的图哈

![bugly](https://user-images.githubusercontent.com/19421422/87010397-17e32100-c1f9-11ea-8f41-98f9daf67648.png)

正常调用估计没什么问题, 我们工程是用`storyboard`创建的`scrollView`, 嵌套调用了多层`scrollView`,`tableView`;然后就是`VC`调用的时候多次更新子视图和父视图的`scrollView`中`constraint`/`contentSize`;所以出现此现象的情况可能比较极端, 希望作者可以修改成`strong`, 更新版本, 解决这个问题;

当然, 如果有其他思路, 可以回复我, 我会继续关注这个`bug`;

**Comment by xing3523** [comment]
我这边只有iOS13的系统，场景也可能没有你的复杂，没有复现出来，不确定是系统版本或是特殊场景或是什么其他原因，不过改为strong也没有问题，这边先更新了版本，你可以先尽量试试之前版本看能不能找到复现步骤，再升级版本看看是不是这个原因。如果还是不行的话，你也可以先本地修改调试确定下问题或者抽个demo出来我再具体看看。有结果的话请再回复下

**Comment by binzi56** [comment]
emm, 👌
